name: app_absent
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.2
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  lottie: ^3.3.1
  


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/absent.png"
  
  min_sdk_android: 21 # android min sdk min:16, default 21

 
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/bg_screen3.jpg
    - assets/images/absent.png
    - assets/images/logo_ppkd.png
    - assets/images/lottie_logo1.json
    


